routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::resource('notifications', 'NotificationController');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('process', 'ProcessController', [
        'process' => 'teamId'
    ]);

    Route::get('/team/{teamId}/process/create', 'ProcessController@create')
        ->name('process_create');
    Route::post('/team/{teamId}/process', 'ProcessController@store')
        ->name('process_store');

    Route::get('/', 'ProcessController@overview')
        ->name('team_overview');
    Route::get('/home', 'ProcessController@overview'); //注册完成后自动跳转到这个地址
    Route::get('/team/{teamId}', 'ProcessController@team')
        ->name('team_processes');

    Route::get('/process/start/{id}', 'ProcessController@start');
    Route::get('/process/reload/{id}', 'ProcessController@reload');
    Route::get('/process/restart/{id}', 'ProcessController@restart');
    Route::get('/process/stop/{id}', 'ProcessController@stop');

    Route::get('/process/log/{id}', 'ProcessLogController@log');
    Route::get('/process/log/stdout/{id}', 'ProcessLogController@stdout');
    Route::get('/process/log/stderr/{id}', 'ProcessLogController@stderr');
});
Route::resource('setting', 'SettingController');

app/Http/Controllers/ProcessController.php
<?php

namespace App\Http\Controllers;

use Log;
use Illuminate\Http\Request;
use App\Core\Deploy;
use App\Core\SupervisordRPCFactory;
use App\Model\Process;
use App\Model\Team;
use App\Http\Services\ProcessService;
use Supervisor\Api;

/**
 *
 */
class ProcessController extends Controller
{
    /**
     * @var Deploy
     */
    private $deploy;

    private $supervisordRpc;

    /**
     *
     * 处理进程的服务
     *
     * @var ProcessService
     */
    private $processService;

    public function __construct(Deploy $deploy)
    {
        // parent::__construct();
        $this->deploy = $deploy;
        $this->processService = new ProcessService();
        $factory = new SupervisordRPCFactory();
        $this->supervisordRpc = $factory->create();
    }

    public function index()
    {
        return $this->overview();
    }

    /**
     *
     */
    public function team($teamId = 0)
    {
        $user = \Auth::user();
        $teamBuilder = $user->team;
        if (0 == $teamId)
            $team = $teamBuilder->first();
        else
            $team = $teamBuilder->where('id', $teamId)->first();
        $permissions = $team->pivot->role->permissions->all();

        Log::debug("User {$user->id} ", ['user' => $user]);
        Log::debug("Team {$team->id}", ['team' => $team]);
        Log::debug("Permissions ", ['permissions' => $permissions]);

        return view("process/index", [
            "permissions" => $permissions,
            "processes" => $this->processService->fetchProcessList($user, $teamId)
        ]);
    }

    public function overview()
    {
        $userId = \Auth::id();
        $user = $this->processService->fetchTeamProcessListByUserId($userId);

        return view("process/overview", [
            "teams" => $user->team
        ]);
    }

    public function create($teamId)
    {
        $process = new Process();
        $process->process_number = 1;
        $process->deploy = Process::DEPLOY_COMMAND;
        return view("process/create", [
            'teamId' => $teamId,
            'process' => $process
        ]);
    }

    /**
     *
     */
    public function store($teamId, Request $request)
    {
        $owner = \Auth::user();
        $team = Team::find($teamId);
        $data = $request->all();

        $data['owner_id'] = $owner->id;
        $data['team_id'] = $team->id;
        $process = Process::create($data);
        $this->deploy->do($process);

        return redirect()->route("process.index", []);
    }

    /**
     *
     */
    public function edit($processId)
    {
        $process = Process::find($processId);
        return view('process/edit', [
            'process' => $process
        ]);
    }

    /**
     *
     */
    public function update($processId, Request $request)
    {
        $process = Process::find($processId);
        $process->update($request->all());

        $this->deploy->do($process);
        return redirect()->route("process.edit", [$process->id]);
    }

    public function destroy($processId)
    {
        $process = Process::find($processId);
        $this->deploy->remove($process);
        $process->delete();
        return response()->json([
            "message" => "ok"
        ]);
    }

    public function stop($id)
    {
        $process = Process::find($id);
        $response = $this->supervisordRpc->stopProcess(
            $process->identifier, 
            false
        );
    }

    public function start($id)
    {
        $process = Process::find($id);
        $response = $this->supervisordRpc->startProcess(
            $process->identifier, 
            false
        );
    }

    public function restart($id)
    {
        $process = Process::find($id);
        $response = $this->supervisordRpc->stopProcess(
            $process->identifier, 
            true
        );

        Log::info(var_export($response, true));

        $response = $this->supervisordRpc->startProcess(
            $process->identifier, 
            true
        );

        Log::info(var_export($response, true));
    }

    public function reload($id)
    {
        $process = Process::find($id);
    }
}

resources/views/process/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="{{route('process.index')}}">Process</a></li>
                <li class="active">Add</li>
            </ol>
            <form action="{{route('process_store', [$teamId])}}" method="POST" enctype="application/x-www-form-urlencoded">
                @component("process.form", ["process" => $process]) @endcomponent
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/process/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="{{route('process.index')}}">Process</a></li>
                <li class="active">Edit</li>
            </ol>
            <form action="{{ route("process.update", [$process->id]) }}" method="POST" enctype="application/x-www-form-urlencoded">
            @component("process.form", ["process" => $process])
            {{ method_field('PUT') }}
            @endcomponent
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/process/form.blade.php
            <div class="form-group">
                <label for="identifier">进程ID</label>
                <input class="form-control" name="identifier" value="{{$process->identifier}}"></input>
            </div>
            <div class="form-group">
                <label for="deploy_type">部署类型</label>
                <select class="form-control" name="deploy" id="deploy">
                    <option value="command">Command</option>
                    <option value="code">Code</option>
                    <option value="zip">ZIP</option>
                </select>
            </div>
            <div class="form-group deploy_command">
                <label for="code">命令行</label>
                <textarea class="form-control" name="command" placeholder="nginx">{{$process->command}}</textarea>
            </div>
            <div class="form-group deploy_code" stype="display: none;">
                <label for="code">Shell脚本</label>
                <textarea class="form-control" name="code">{{$process->code}}</textarea>
            </div>
            <div class="form-group">
                <label for="process_number">进程数量</label>
                <input class="form-control" type="text" name="process_number" value="{{$process->process_number}}"></input>
            </div>
            <button type="submit" class="btn btn-primary pull-right">发布进程</button>
            {{ csrf_field() }}
            {{$slot}}

            <script>

function activeDeploy(activeType)
{
    var deploy = ['command', 'code'];
    for (var i = 0, size = deploy.length; i < size; i++) {
        var type = deploy[i];
        var commandElement = $(".deploy_" + type);
        var className = ".deploy_" + type
        if (type == activeType)
            $(className).css("display", "block");
        else
            $(className).css("display", "none");
    }
}

$(document.body).ready(function() {
    var process =
    @php
    echo json_encode($process);
    @endphp
    
    $("#deploy").change(function(event) {
        var currentDeployType = $(event.currentTarget).val()
        activeDeploy(currentDeployType)
    })
    activeDeploy(process.deploy.toLowerCase())
    $("#deploy").val(process.deploy.toLowerCase())
})
</script>

resources/views/process/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="clearfix">
            </div>
            <div class="panel panel-default clearfix">
                @if (head(array_where($permissions, function($value, $key) { return $value->slug == 'create.process'; })))
                <div class="panel-heading clearfix">
                    <a class="btn btn-primary pull-right" href="/process/create">启动新进程</a>
                </div>
                @endif
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Identifier</th>
                                <th>状态</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($processes as $process)
                            <tr class="process-row">
                                <td>
                                    @if (head(array_where($permissions, function($value, $key) { return $value->slug == 'create.process'; })))
                                        <a href="{{ route('process.edit', [$process->id]) }}">{{$process->identifier}}</a>
                                    @else
                                        {{$process->identifier}}
                                    @endif
                                </td>
                                <td class="process-status">{{$process->status}}</td>
                                <td class="process-action">
                                    <div class="btn-group pull-right">
                                        @if (head(array_where($permissions, function($value, $key) { return $value->slug == 'create.process'; })))
                                            @if ($process->canStart())
                                            <button type="button"
                                                class="btn btn-default toggle-drop start"
                                                onclick="startProcess('{{action('ProcessController@start', [$process->id])}}')">
                                                启动
                                            </button>
                                            @elseif ($process->canStopOrRestart())
                                            <button type="button" 
                                                class="btn btn-default toggle-drop restart"
                                                onclick="restartProcess('{{action('ProcessController@reload', [$process->id])}}')">
                                                重启
                                            </button>
                                            <button type="button" 
                                                class="btn btn-default toggle-drop stop"
                                                onclick="stopProcess('{{action('ProcessController@stop', [$process->id])}}')">
                                                停止
                                            </button>
                                            @endif
                                            <button type="button" 
                                                class="btn btn-default toggle-drop log"
                                                onclick="readProcessLog('{{action('ProcessLogController@log', [$process->id])}}')">
                                                查看日志
                                            </button>
                                            <button type="button"
                                                class="btn btn-default dropdown-toggle" 
                                                data-toggle="dropdown">
                                                <span class="caret"></span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu"
                                                aria-labelledby="process-menu-{{$process->id}}">
                                                @if (head(array_where($permissions, function($value, $key) { return $value->slug == 'create.process'; })) && $process->canStopOrRestart())
                                                <li><a href="javascript:reload_process({{action('ProcessController@restart', [$process->id])}});">平滑重启</a></li>
                                                @endif
                                                <li>
                                                    <a href="javascript:delete_process('{{route('process.destroy', [$process->id])}}');">删除</a>
                                                </li>
                                            </ul>
                                        @else
                                        <button type="button" 
                                            class="btn btn-default toggle-drop log"
                                            onclick="readProcessLog('{{action('ProcessLogController@log', [$process->id])}}')">
                                            查看日志
                                        </button>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function delete_process(deleteProcessUrl)
{
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $.post(deleteProcessUrl, {"_method": "DELETE"})
        .done(function(res) {
            console.log(res)
        })
}

function startProcess(startProcessUrl)
{
    $.get(startProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function reloadProcess(reloadProcessUrl)
{
    $.get(reloadProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function restartProcess(restartProcessUrl)
{
    $.get(restartProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function stopProcess(stopProcessUrl)
{
    $.get(stopProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function readProcessLog(readProcessLogUrl) {
    document.location.href = readProcessLogUrl;
}
</script>
@endsection

resources/views/process/log.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="{{route('process.index')}}">Process</a></li>
                <li class="active">Log</li>
            </ol>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- Nav tabs -->
                    <ul id="stdtab" class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#stdout"  data-pipe="stdout" aria-controls="stdout" role="tab" data-toggle="tab">Stdout</a></li>
                        <li role="presentation"><a href="#stderr" data-pipe="stderr" aria-controls="stderr" role="tab" data-toggle="tab">Stderr</a></li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="stdout">
                            <pre>{{$log}}</pre>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="stderr">
                            <pre></pre>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
<script>

$('#stdtab a').click(function (e) {
  e.preventDefault()
  $pipe = $(e.target).attr("data-pipe")
  var stdout = "{{action('ProcessLogController@stdout', [$process->id])}}";
  var stderr = "{{action('ProcessLogController@stderr', [$process->id])}}";

  if ($pipe == "stderr") {
      $.get(stderr).done(function(rsp) {
        $("#" + $pipe + " pre").html(rsp)
      })
  }
//   $(this).tab('show')
})
</script>
@endsection

resources/views/process/overview.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        @foreach ($teams as $team)
            @component('process/processes', ['processes' => $team->process, 'team' => $team])    
            @endcomponent
        @endforeach
        </div>
    </div>
</div>
<script>
function delete_process(deleteProcessUrl)
{
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $.post(deleteProcessUrl, {"_method": "DELETE"})
        .done(function(res) {
            console.log(res)
        })
}

function startProcess(startProcessUrl)
{
    $.get(startProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function reloadProcess(reloadProcessUrl)
{
    $.get(reloadProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function restartProcess(restartProcessUrl)
{
    $.get(restartProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function stopProcess(stopProcessUrl)
{
    $.get(stopProcessUrl).done(function(res) {
        document.location.reload();
    })
}

function readProcessLog(readProcessLogUrl) {
    document.location.href = readProcessLogUrl;
}
</script>
@endsection

resources/views/process/processes.blade.php
<div class="clearfix">
</div>
<div class="panel panel-default clearfix">
    <div class="panel-heading clearfix">
        <div class="pull-left">{{$team->name}}</div>
        @if ($team->pivot->role->permissions->where('slug', 'create.process')->isNotEmpty())
        <a class="btn btn-primary pull-right" href="{{route('process_create', [$team->id])}}">启动新进程</a>
        @endif
    </div>
    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Identifier</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($processes as $process)
                <tr class="process-row">
                    <td>
                        @if ($team->pivot->role->permissions->where('slug', 'create.process')->isNotEmpty())
                            <a href="{{ route('process.edit', [$process->id]) }}">{{$process->identifier}}</a>
                        @else
                            {{$process->identifier}}
                        @endif
                    </td>
                    <td class="process-status">
                        @if ($process != null)
                        {{$process->supervisorStatus()}}
                        @endif
                    </td>
                    <td class="process-action">
                        <div class="btn-group pull-right">
                            @if ($team->pivot->role->permissions->where('slug', 'create.process')->isNotEmpty())
                                @if ($process->canStart())
                                <button type="button"
                                    class="btn btn-default toggle-drop start"
                                    onclick="startProcess('{{action('ProcessController@start', [$process->id])}}')">
                                    启动
                                </button>
                                @elseif ($process->canStopOrRestart())
                                <button type="button" 
                                    class="btn btn-default toggle-drop restart"
                                    onclick="restartProcess('{{action('ProcessController@reload', [$process->id])}}')">
                                    重启
                                </button>
                                <button type="button" 
                                    class="btn btn-default toggle-drop stop"
                                    onclick="stopProcess('{{action('ProcessController@stop', [$process->id])}}')">
                                    停止
                                </button>
                                @endif
                                <button type="button" 
                                    class="btn btn-default toggle-drop log"
                                    onclick="readProcessLog('{{action('ProcessLogController@log', [$process->id])}}')">
                                    查看日志
                                </button>
                                <button type="button"
                                    class="btn btn-default dropdown-toggle" 
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu"
                                    aria-labelledby="process-menu-{{$process->id}}">
                                    <li><a href="javascript:reload_process({{action('ProcessController@restart', [$process->id])}});">平滑重启</a></li>
                                    <li>
                                        <a href="javascript:delete_process('{{route('process.destroy', [$process->id])}}');">删除</a>
                                    </li>
                                </ul>
                            @else
                            <button type="button" 
                                class="btn btn-default toggle-drop log"
                                onclick="readProcessLog('{{action('ProcessLogController@log', [$process->id])}}')">
                                查看日志
                            </button>
                            @endif
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>